CREATE TABLE `sales_behavior_data` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` varchar(255) DEFAULT NULL,
  `order_date` date DEFAULT NULL,
  `brand` varchar(255) DEFAULT NULL,
  `model_name` varchar(255) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `size` int DEFAULT NULL,
  `color` varchar(100) DEFAULT NULL,
  `base_price_usd` int DEFAULT NULL,
  `discount_percent` int DEFAULT NULL,
  `final_price_usd` decimal(12,2) DEFAULT NULL,
  `units_sold` int DEFAULT NULL,
  `revenue_usd` decimal(12,2) DEFAULT NULL,
  `payment_method` varchar(255) DEFAULT NULL,
  `sales_channel` varchar(255) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `customer_income_level` varchar(100) DEFAULT NULL,
  `customer_rating` decimal(12,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_id` (`order_id`),
  CONSTRAINT `sales_behavior_data_chk_1` CHECK ((`discount_percent` between 0 and 100))
)